export const locationsList = [
    "1 ozdoby, drzwi",
    "2 promocja, napoje",
    "3 kasa",
    "4 ravi, york, sinpo",
    "5 kosze, suszarki",
    "6 ravi, gąbki",
    "7 sarantis worki",
    "8 ravi worki",
    "9 płyny, papiery",
    "10 pasty",
    "11 chemia gospodarcza",
    "12 tacki, sztućce",
    "13 gondola 1",
    "14 czajniki, garnki, patelnie",
    "15 kieliszki, naczynia",
    "16 talerze kubki",
    "17 lampki, patery",
    "18 wysposażenie kuchni",
    "19 patelnie, deski",
    "20 miski",
    "21 zwieger",
    "22 maty, ceraty",
    "23 dywany",
    "24 panele, uszczelki",
    "25 gładzie, płytki, sypkie",
    "26 wycieraczki",
    "27 kaźmierczak",
    "28 pace, półki",
    "29 karnisze",
    "30 tapety",
    "31 effector listwy",
    "32 decora listwy",
    "33 tesa, podkłady",
    "34 taśmy",
    "35 kaem wałki, pędzle",
    "36 kaem szpachle",
    "37 łaty pro",
    "38 chemia budowlana",
    "39 wiadra, nexler",
    "40 pro poziomice",
    "41 mieszadła, tarcze, szczotki",
    "42 siekiery, piły, młotki",
    "43 klucze, narzędzia, wiertła",
    "44 folie, taśmy",
    "45 premar",
    "46 wentylacja",
    "47 żarówki",
    "48 złączki",
    "49 wtyczki, gniazdka",
    "50 przedłużacze, przewody",
    "51 pręty, narożniki",
    "52 rader",
    "53 papiery ścierne",
    "54 liny, łańcuchy",
    "55 szczotki, szekle",
    "56 akc. Gah",
    "57 kłódki, klamki",
    "58 kubala",
    "59 szczotpol, profile",
    "60 simpson, drabiny",
    "61 śruby, wkręty",
    "62 podkładki, śruby",
    "63 akc. Do profili, wkrety",
    "64 kanalizacja kw pp",
    "65 galeco+ rury",
    "66 kanalizacja kosze",
    "67 syfony, złącze pe",
    "68 galeco rynny",
    "69 nity, gwoździe, kołki",
    "70 wężyki, pp",
    "71 kotwy, kołki",
    "72 ega",
    "73 pp rury, otuliny, miedź",
    "74 ocynk, miedź",
    "75 zawory",
    "76 shop line",
    "77 stanley",
    "78 narzędzia elektyczne",
    "79 biurko narzędzia",
    "80 biurko hydraulika",
    "81 baterie",
    "82 bisk, galicja",
    "83 kabiny, lustra, zlewy met",
    "84 wystawki, nagrzewnice",
    "85 doniczki",
    "86 nagrzewnice",
    "87 foremki, blaszki",
    "88 meble wyspa 1",
    "89 meble wyspa 2",
    "90 wanny, zlewy, umywalki",
    "91 kompakty",
    "92 grabie, łopaty, trzonki",
    "93 biopon, bros",
    "94 celfast",
    "95 plandeki, tablice, konewki",
    "96 koszulki, wkładki",
    "97 węże, akc.ogrodowe",
    "98 maski, buty",
    "99 kalosze, skrzynki",
    "100 skarpety, koszule",
    "101 rękawiczki, czapki",
    "102 kieszeń",
    "103 klamki",
    "104 kurtki, spodnie",
    "105 spodnie, ochraniacze, buty",
    "106 spraye",
    "107 sinpo",
    "108 śnieżka barwy natury",
    "109 śnieżka plamoodporna",
    "110 magazynek farby",
    "111 biurko farby",
    "112 wyspa emulsje białe",
    "113 wyspa emulsje, impregnaty, przecena",
    "114 magnat",
    "115 dulux kolory",
    "116 śnieżka olejna",
    "117 śnieżka emulsje, gładzie",
    "118 dębica akrylowe, impregnaty",
    "119 beckers kolory",
    "120 grunty, pianki",
    "121 rozpuszczalniki, v33",
    "122 altax olejne",
    "123 sadolin",
    "124 vidaron",
    "125 fugi ceresit, mapei",
    "126 boll",
    "127 jurga",
    "128 silikony, pianki",
    "129 boramax+silikony",
    "130 magazynek",
    "131 styropian, papa, taczki",
    "132 magazyn namiot",
    "133 magazyn hala",
    "134 plac za siatką",
    "135 plac kanalizacja",
    "136 wolne",
    "137 wolne",
    "138 wolne"
]
