export const locationsList = [
    "1 – Nasiona , Nawozy , Łopaty do Śniegu",
    "2, 3  - Broil King , Grile",
    "4 – Energ. Lustra , Neo , Tesa , Favorite , Podkładki Filcowe",
    "5 - Kasa, Klamki, Taczki",
    "6 - Miary, Energia Batony, Rękawice, Cała Reszta",
    "7 - Szafki, Umywalki, Zestawy Podtynkowe, Czysta Lazienka",
    "8 - Lustra, Akcesoria Łazienkowe, Bisk",
    "9 - Uchwyty, Węże, Słuchawki",
    "10 - Baterie, Deszczownice",
    "11 - Wanny, Umywalki, Kompakty, Zlewy, Odpływy Liniowe, Zawory, DEDRA Akcesoria",
    "12 - Lada – Hydraulika",
    "13 - Narzędzia AEG, TRYTON, DEWALT, DEDRA",
    "14 - LOB",
    "15 - BORYSZEW",
    "16 - OC",
    "17 - Miedź, Mosiądz",
    "18 - Zawory",
    "19 - Uszczelki, Węże, Syfony",
    "20 - Koelner, Fisher",
    "21 - Śruby, Nakrętki, Podkładki",
    "22 - Kotwy, Gwoździe",
    "23 - KW, KZ, PE",
    "24 - Wyspa – Sprzęt Elektr.",
    "25 - Kanalizacja, Kolanka, Rurki",
    "26 - Kołki",
    "27 - Wkręty",
    "28 - Rawplug",
    "29 - Kazimierczak",
    "30 - Vidaron",
    "31 - Altaxy, Decora Listwy",
    "32 - Plandeki",
    "33 - Drabiny, Pręty",
    "34 - Narożniki",
    "35 - Papier Ścierny",
    "36 - GAH 1",
    "37 - GAH 2",
    "38 - ShopLine, Skrzynki",
    "39 - Żarówki",
    "40 - Przedłużacze, Gniazdka, Włączniki",
    "41 - Przew. Elektryczne",
    "42 - Łańcuchy, Linki",
    "43 - Listwy Wentylac., Korytka, Uszczelki, Rury",
    "44 - Wentylacja DOSPEL, AVENTA, Wentylatory",
    "45 - Opaski, Uchwyty, Halogeny, Dzwonki, Wtyczki",
    "46 - Wiertła",
    "47 - Rączki, Wałki, Pędzle, Kuwety",
    "48 - Taśmy, Folie",
    "49 - Szczotki, Pace, Krzyżyki",
    "50 - Poziomice, Piły",
    "51 - Dłuta, Zszywacze, Siekiery, Młotki",
    "52 - Wkrętaki, Szczypce",
    "53 - Szczotki, Tarcze",
    "54, 55 - Kubala 1, Kubala 2",
    "56 - Rolety",
    "57 - Decora (Listwy i Zakończenia)",
    "58 - Profile",
    "59 - Silicony Bostik, Ceresit",
    "60 - Fugi",
    "61 - Miary, Kątowniki",
    "62 - Sadolin, Vidaron, Altax Imp.",
    "63 - Podkłady, Folie, Wałki",
    "64 - Panele",
    "65 - Kosz – Wyprzedaże, Kubala, Słoiki",
    "66 - Przedłużacze, Agregaty, Koła, Dedra, Grabie, Łopaty, Trzonki",
    "67 - Wystawka – Szafki",
    "68 - Wyspa, Grzejniki, Piecyki",
    "69 - Samochodówka",
    "70 - Ravi, York, Jan Nidezbędny",
    "71 - Chemia, Ravi",
    "72 - Chemia",
    "73 - Brovin",
    "74 - Forte Mill, Serwetki",
    "75 - Bross, Biopon, Morus, Feniks, Płyny, Drzwi, Pojemniki",
    "76 - Wędkarski, Wyspa Wędki, Chodaki, Gumofilce",
    "77 - Dywany, Ceraty, Sympatex",
    "78 - Art. Świąteczne, EkoGroszek",
    "79 - Formy Do Ciast, Maty, Torebki, Serwetki",
    "80 - Ambition, Porcelana, Kubki",
    "81 - Ambition, Szkło, Noże, Garnki",
    "82 - Ręczniki, Poduszki",
    "83 - Chodaki, Dywany, Wycieraczki",
    "84 - Patelnie – Royal, Ambition, Zwieger – Garnki, Czajniki",
    "85 - Suszarki, Kosze, Miski",
    "86 - Galicja Platiki, Szkło",
    "87 - Garnki Art. Kuchenne",
    "88 - Ambition Formy, Pojemniki Dzbanki, Czajniki",
    "89 - Galicja Kubki, Dzbanki",
    "90 - Ravi – artykuły, Worki, Blaszki, Jednorazówki",
    "91 - Stol-Kar, Kleje do Tapet",
    "92 - Płytki, Gress, Tapety, Worki",
    "93 - BHP – Ostrz. Kurtki, Bluzy, Koszule",
    "94 - BHP – Spodnie, Płaszcze, Koszulki",
    "95 - Gondola 2",
    "96 - Gondola 1",
    "97 - BHP – Obuwie",
    "99 - Sadolin, Dulux",
    "100 - Grunty, Rozpuszczalniki",
    "101 - SYPKIE, Kleje",
    "102 - Izohan, Wiadra, Kasty",
    "103 - Piachy, Tektura",
    "104 - Szczotki, Grunty, Stretch",
    "105 - Magnat C, Magnat KL",
    "106 - Śnież. Plamoodporna, Jedynka",
    "107 - Tikurilla, Brokaty, Zapasy",
    "108 - Koloranty, Cementy, Goldband",
    "109 - Dorex, Farby, Podesty",
    "110 - Piachy, Farby",
    "111 - Beckers",
    "112 - Dębica",
    "113 - Śnieżka – Olejne",
    "114 - Śnieżka - BN",
    "115 - Piachy Foveo",
    "116 - Gwoździe, Taśmy, Farby",
    "117 - Gwoździe, Pręty, Tynki, Farby",
    "118 - Narożniki",
    "119 - Drzwi, Folie, Drabiny, Podkłady",
    "120 - Nidzica, dodatkowy 1",
    "121 - Nidzica, dodatkowy 2",
    "122 - Nidzica, dodatkowy 3",
    "123 - Nidzica, dodatkowy 4",
    "124 - Nidzica, dodatkowy 5",
    "125 - Nidzica, dodatkowy 6",
];